apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: middleware-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: middleware
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
      - name: middleware-svc
        image: middleware:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        - containerPort: 8091
        env:
          - name: NEWS_SERVICE_URI
            value: http://news-service-svc.default.svc.cluster.local
          - name: NEWS_SERVICE_PORT
            value: '3000'
---
apiVersion: v1
kind: Service
metadata:
  name: middleware-svc
  labels:
    app: middleware-svc
  namespace: default
spec:
  selector:
    app: middleware
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
    name: middleware-port
  - port: 8091
    protocol: TCP
    targetPort: 8091
    name: middleware-socket
