apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: polisen-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: polisen
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
      - name: polisen-svc
        image: polisen-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4002
        env:
          - name: NEWS_SERVICE_URI
            value: http://news-service-svc.default.svc.cluster.local
          - name: NEWS_SERVICE_PORT
            value: '3000'
---
apiVersion: v1
kind: Service
metadata:
  name: polisen-svc
  labels:
    app: polisen-svc
  namespace: default
spec:
  selector:
    app: polisen
  ports:
  - port: 4002
    protocol: TCP
    targetPort: 4002
    name: polisen-port
