apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twitter-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: twitter
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
      - name: twitter-svc
        image: twitter-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4003
        env:
          - name: NEWS_SERVICE_URI
            value: http://news-service-svc.default.svc.cluster.local
          - name: NEWS_SERVICE_PORT
            value: '3000'
---
apiVersion: v1
kind: Service
metadata:
  name: twitter-svc
  labels:
    app: twitter-svc
  namespace: default
spec:
  selector:
    app: twitter
  ports:
  - port: 4003
    protocol: TCP
    targetPort: 4003
    name: twitter-port
